// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SuntonESP32_example

#include <stdio.h>
#include "../ui.h"

#define SINE_WAVE_CYCLE 60
#define SAW_WAVE_CYCLE 50

const lv_coord_t saw_wave_value[] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49};


const lv_coord_t sine_wave_value[] = {0,5,10,15,20,25,29,33,37,40,43,45,47,48,49,50,49,48,47,45,43,40,37,33,29,25,20,15,10,5,0,-5,-10,-15,-20,-24,-29,-33,-37,-40,-43,-45,-47,-48,-49,-50,-49,-48,-47,-45,-43,-40,-37,-33,-29,-24,-20,-15,-10,-5,
0,5,10,15,20,25,29,33,37,40,43,45,47,48,49,50,49,48,47,45,43,40,37,33,29,25,20,15,10,5,0,-5,-10,-15,-20,-24,-29,-33,-37,-40,-43,-45,-47,-48,-49,-50,-49,-48,-47,-45,-43,-40,-37,-33,-29,-24,-20,-15,-10,-5,
0,5,10,15,20,25,29,33,37,40,43,45,47,48,49,50,49,48,47,45,43,40,37,33,29,25,20,15,10,5,0,-5,-10,-15,-20,-24,-29,-33,-37,-40,-43,-45,-47,-48,-49,-50,-49,-48,-47,-45,-43,-40,-37,-33,-29,-24,-20,-15,-10,-5,
0,5,10,15,20,25,29,33,37,40,43,45,47,48,49,50,49,48,47,45,43,40,37,33,29,25,20,15,10,5,0,-5,-10,-15,-20,-24,-29,-33,-37,-40,-43,-45,-47,-48,-49,-50,-49,-48,-47,-45,-43,-40,-37,-33,-29,-24,-20,-15,-10,-5,
0,5,10,15,20,25,29,33,37,40,43,45,47,48,49,50,49,48,47,45,43,40,37,33,29,25,20,15,10,5,0,-5,-10,-15,-20,-24,-29,-33,-37,-40,-43,-45,-47,-48,-49,-50,-49,-48,-47,-45,-43,-40,-37,-33,-29,-24,-20,-15,-10,-5,
0,5,10,15,20,25,29,33,37,40,43,45,47,48,49,50,49,48,47,45,43,40,37,33,29,25,20,15,10,5,0,-5,-10,-15,-20,-24,-29,-33,-37,-40,-43,-45,-47,-48,-49,-50,-49,-48,-47,-45,-43,-40,-37,-33,-29,-24,-20,-15,-10,-5,
0,5,10,15,20,25,29,33,37,40,43,45,47,48,49,50,49,48,47,45,43,40,37,33,29,25,20,15,10,5,0,-5,-10,-15,-20,-24,-29,-33,-37,-40,-43,-45,-47,-48,-49,-50,-49,-48,-47,-45,-43,-40,-37,-33,-29,-24,-20,-15,-10,-5,
0,5,10,15,20,25,29,33,37,40,43,45,47,48,49,50,49,48,47,45,43,40,37,33,29,25,20,15,10,5,0,-5,-10,-15,-20,-24,-29,-33,-37,-40,-43,-45,-47,-48,-49,-50,-49,-48,-47,-45,-43,-40,-37,-33,-29,-24,-20,-15,-10,-5};

int idx = 0;
lv_chart_series_t *data1;


void reset_chart(lv_obj_t *chart) {
    while(data1) {
        lv_chart_remove_series(chart, data1);
        data1 = lv_chart_get_series_next(chart, NULL);
    }
    data1 = lv_chart_add_series(chart, lv_palette_main(LV_PALETTE_GREEN), LV_CHART_AXIS_PRIMARY_X);
}

void draw_graph(lv_timer_t *timer) {
    int value[60] = {0,5,10,15,20,25,29,33,37,40,43,45,47,48,49,50,49,48,47,45,43,40,37,33,29,25,20,15,10,5,0,-5,-10,-15,-20,-24,-29,-33,-37,-40,-43,-45,-47,-48,-49,-50,-49,-48,-47,-45,-43,-40,-37,-33,-29,-24,-20,-15,-10,-5};
    lv_obj_t *chart = (lv_obj_t *)timer->user_data;

    // lv_chart_set_next_value(chart, data1, value[idx%60]);
    lv_chart_set_next_value(chart, data1, saw_wave_value[idx%SAW_WAVE_CYCLE]);
    //lv_chart_set_next_value(chart, data1, value[idx%60]);
    // lv_chart_set_next_value2(chart, data1, idx, saw_wave_value[idx%SAW_WAVE_CYCLE]);
    idx++;
    if(idx >= 600) {
        reset_chart(chart);
        idx = 0;
    }
    lv_chart_refresh(chart);
    
}
void make_sine_wave(lv_obj_t *tab) {
    lv_obj_t *chart = lv_chart_create(tab);
    lv_obj_set_size(chart, 480, 500);
    lv_obj_center(chart);
    //lv_chart_set_type(chart, LV_CHART_TYPE_LINE);
    lv_chart_set_type(chart, LV_CHART_TYPE_SCATTER);
    lv_chart_set_point_count(chart, 600);
    lv_chart_set_range(chart, LV_CHART_AXIS_PRIMARY_Y, -50, 50);
    lv_chart_set_update_mode(chart, LV_CHART_UPDATE_MODE_CIRCULAR);
    
    lv_obj_set_style_radius(chart, 0, LV_PART_INDICATOR);  // Set radius to 0 to hide points
    lv_obj_set_style_border_width(chart, 0, LV_PART_INDICATOR); // Set border width to 0 to hide border



    data1 = lv_chart_add_series(chart, lv_palette_main(LV_PALETTE_GREEN), LV_CHART_AXIS_PRIMARY_X);

    lv_timer_t *timer = lv_timer_create(draw_graph, 10, chart);
    lv_timer_set_repeat_count(timer, -1);  
}



void make_line_chart(lv_obj_t *tab) {
    int value[19] = {0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 80, 70, 60, 50, 40, 30, 20, 10, 0};
    int value2[19] = {0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0};

    lv_obj_t *chart = lv_chart_create(tab);
    lv_obj_set_size(chart, 600, 400);
    lv_obj_center(chart);
    lv_chart_set_type(chart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(chart, 20);

    lv_chart_series_t *data1 = lv_chart_add_series(chart, lv_palette_main(LV_PALETTE_RED), LV_CHART_AXIS_PRIMARY_Y);
    lv_chart_series_t *data2 = lv_chart_add_series(chart, lv_palette_main(LV_PALETTE_BLUE), LV_CHART_AXIS_SECONDARY_Y);

    for(int idx=0;idx <19; idx++) {
        lv_chart_set_next_value(chart, data1, value[idx]);
        lv_chart_set_next_value(chart, data2, value2[idx]);
    }
    lv_chart_refresh(chart);
    
}

void make_chart(lv_obj_t *tab) {
    lv_obj_t *chart = lv_chart_create(tab);
    lv_obj_set_size(chart, 600, 480);
    lv_obj_align(chart, LV_ALIGN_CENTER, -30, -30);
    lv_chart_set_range(chart, LV_CHART_AXIS_PRIMARY_Y, -100, 100);

    lv_obj_set_style_size(chart, 0, LV_PART_INDICATOR);

    lv_chart_series_t *data = lv_chart_add_series(chart, lv_palette_main(LV_PALETTE_RED), LV_CHART_AXIS_PRIMARY_Y);

    int pcnt = sizeof(sine_wave_value) / sizeof(sine_wave_value[0]);
    lv_chart_set_point_count(chart, pcnt);
    lv_chart_set_ext_y_array(chart, data, (lv_coord_t *)sine_wave_value);
}

void charts_Screen_init(void) {
    char *tabview_tile[2] = {"SineWave", "SawWave"};
    lv_obj_t *tab_objs[2];

    charts_init_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(charts_init_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    make_chart(charts_init_Screen);
}