// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SuntonESP32_example

#include "../ui.h"
#include <stdbool.h>
#include "esp_log.h"

#define MASK_WIDTH 100
#define MASK_HEIGHT 45
#define state_row 2
#define state_col 10
#define state_check(state) ((state)?"O":"X")


static lv_obj_t *modal = NULL;
static lv_style_t style_modal;
static char state_title[11] = {'1', '2', '3', '4', '5', '6', '7','8', '9', '10'};
uint16_t checklist_state = 0b1010111000;

void update_table_cell(uint8_t col) {
    checklist_state ^= (1 << col);
    lv_table_set_cell_value(state_tabel, 1, col, state_check(checklist_state & (1 << col)));
}

void event_table_cell_click(lv_event_t *e) {
    lv_obj_t *obj = lv_event_get_target(e);
    uint32_t col = (uint32_t)lv_event_get_user_data(e);
    update_table_cell(col);
}

// void mbox_event_cb(lv_obj_t *obj, lv_event_t evt) {
//     if(evt == LV_EVENT_DELETE && obj == modal) {
//         lv_obj_del_async(lv_obj_get_parent(modal));
//         modal = NULL;
//     } else if(evt == LV_EVENT_VALUE_CHANGED) {
//         lv_msgbox_start_auto_close(modal, 0);
//     }

// }

// void event_btn(lv_obj_t *btn, lv_event_t evt) {
//     if(evt == LV_EVENT_CLICKED) {
//     }
// }
void event_cb(lv_event_t*e) {
    lv_obj_t *obj = lv_event_get_target(e);
    const char *btn_text = lv_msgbox_get_active_btn_text(obj);
    if(btn_text) {
        LV_LOG_INFO("Button %s Clicked", btn_text);
    }
}

void event_btn(lv_event_t *e) {
    if (modal == NULL) {
        const char *btns[] = {"A", "B", "C", ""};
        modal = lv_msgbox_create(modal_Screen, "Hello", "Modal", btns, true);
        lv_obj_add_event_cb(modal, event_cb, LV_EVENT_VALUE_CHANGED, NULL);
        lv_obj_center(modal);
    } else {
        lv_obj_clear_flag(modal, LV_OBJ_FLAG_HIDDEN);
    }
//     lv_obj_t * btn = lv_obj_get_child(obj, 0);
//     lv_obj_t * desc = (lv_obj_t * )lv_event_get_user_data(e);
//     ESP_LOGI("TAG", "Label address: %p", (void *)desc);

//     btn_state = !btn_state;

//     if(btn && lv_obj_check_type(btn, &lv_label_class)) {
//         lv_label_set_text(btn, btn_text(btn_state));
//     }
//     if(desc) {
//         lv_label_set_long_mode(desc, desc_scroll(btn_state));
//     }
}


void modal_Screen_screen_init(void)
{
    modal_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(modal_Screen, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *state_tabel = lv_table_create(modal_Screen);
    lv_table_set_row_cnt(state_tabel, state_row);
    lv_table_set_col_cnt(state_tabel, state_col);
    lv_obj_set_width(state_tabel, 800);
    lv_obj_set_height(state_tabel, 100);

    for(int col = 0; col < state_col; col++) { // 테이블 열 개수를 2로 맞춤
        char cell_value[2] = { state_title[col], '\0' }; // 한 글자와 null 종단 문자
        lv_table_set_cell_value(state_tabel, 0, col, cell_value);
        lv_table_set_cell_value(state_tabel, 1, col, state_check(checklist_state & (1 << col)));

        lv_table_get_selected_cell(state_tabel, 1, col);
       // lv_obj_add_event_cb(cell_obj, event_table_cell_click, LV_EVENT_CLICKED, (void *)(uintptr_t)col);
    }
    
    lv_obj_align(state_tabel, LV_ALIGN_CENTER, 0, 0);

    // Button
    lv_obj_t *open_modal_btn = lv_btn_create(modal_Screen);
    lv_obj_set_width(open_modal_btn, 100);
    lv_obj_set_height(open_modal_btn, 50);
    lv_obj_add_event_cb(open_modal_btn, event_btn, LV_EVENT_CLICKED, NULL);
    lv_obj_set_align(open_modal_btn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(open_modal_btn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(open_modal_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    if(modal) {
        lv_obj_add_flag(modal, LV_OBJ_FLAG_HIDDEN);
    }
}