// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SuntonESP32_example

#include "../ui.h"
#include <stdbool.h>
#include "esp_log.h"

#define MASK_WIDTH 100
#define MASK_HEIGHT 45

#define btn_text(state) ((state) ? "ON" : "OFF")
#define desc_scroll(desc) ((desc) ? LV_LABEL_LONG_SCROLL_CIRCULAR:LV_LABEL_LONG_DOT)

static bool btn_state = true;
static bool *desc_scroll_state = &btn_state;

void event_btn(lv_event_t *e) {
    lv_obj_t * obj = lv_event_get_current_target(e);
    lv_obj_t * btn = lv_obj_get_child(obj, 0);
    lv_obj_t * desc = (lv_obj_t * )lv_event_get_user_data(e);
    ESP_LOGI("TAG", "Label address: %p", (void *)desc);

    btn_state = !btn_state;

    if(btn && lv_obj_check_type(btn, &lv_label_class)) {
        lv_label_set_text(btn, btn_text(btn_state));
    }
    if(desc) {
        lv_label_set_long_mode(desc, desc_scroll(btn_state));
    }

}

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Text Label Title
    lv_obj_t *label_title = lv_label_create(ui_Screen2);
    lv_label_set_text(label_title, "This is LVGL with ESP32-8048S070");
    lv_obj_set_width(label_title, 300);
    lv_obj_set_style_text_align(label_title, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_align(label_title, LV_ALIGN_CENTER, 0, -40);
    

    // Text Label Desc
    lv_obj_t *label_desc = lv_label_create(ui_Screen2);
    lv_label_set_long_mode(label_desc, desc_scroll(*desc_scroll_state));
    lv_obj_set_width(label_desc, 150);
    lv_label_set_text(label_desc, "Gangneug-Wonju National University");
    lv_obj_align(label_desc, LV_ALIGN_CENTER, 0, 40);
    ESP_LOGI("TAG", "Label address: %p", (void *)label_desc);

    // Button
    ui_Button2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_add_event_cb(ui_Button2, event_btn, LV_EVENT_CLICKED, label_desc);
    lv_obj_set_align(ui_Button2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    lv_obj_t *btn_label = lv_label_create(ui_Button2);

    lv_label_set_text(btn_label, btn_text(btn_state));
    lv_obj_center(btn_label);

}
