// // This file was generated by SquareLine Studio
// // SquareLine Studio version: SquareLine Studio 1.3.0
// // LVGL version: 8.3.6
// // Project name: SuntonESP32_example

// #include "ui.h"
// #include "ui_helpers.h"

// ///////////////////// VARIABLES ////////////////////

// // SCREEN: ui_Screen1
// void ui_Screen1_screen_init(void);
// lv_obj_t *ui_Screen1;
// lv_obj_t *ui_Button2;
// lv_obj_t *ui_Button1;
// lv_obj_t *ui_Button4;
// lv_obj_t *ui_Button3;
// lv_obj_t *ui_Button6;
// lv_obj_t *ui____initial_actions0;

// ///////////////////// TEST LVGL SETTINGS ////////////////////
// #if LV_COLOR_DEPTH != 16
// #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
// #endif
// #if LV_COLOR_16_SWAP != 0
// #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
// #endif

// ///////////////////// ANIMATIONS ////////////////////

// ///////////////////// FUNCTIONS ////////////////////

// ///////////////////// SCREENS ////////////////////

// void ui_init(lv_disp_t *disp) {
//   lv_theme_t *theme = lv_theme_default_init(
//       disp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
//       false, LV_FONT_DEFAULT);
//   lv_disp_set_theme(disp, theme);
//   ui_Screen1_screen_init();
//   ui____initial_actions0 = lv_obj_create(NULL);
//   lv_disp_load_scr(ui_Screen1);
// }

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SuntonESP32_example

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_Screen1_screen_init(void);
void modal_Screen_screen_init(void);
void setup_set_Screen_screen_init(void);
void tabview_setup_Screen_screen_init(void);
void tabview_grid_Screen_init(void);
void simple_card_game_init(void);
void simple_card_game_main_Screen(void);
void charts_Screen_init(void);

lv_obj_t *ui_Screen1;
lv_obj_t *ui_Button2;
lv_obj_t *ui_Button1;
lv_obj_t *ui_Button4;
lv_obj_t *ui_Button3;
lv_obj_t *ui_Button6;

lv_obj_t *ui_Screen2;
lv_obj_t *label_title;
lv_obj_t *label_desc;
lv_obj_t *label_grad_dsc;
lv_obj_t *ui_Button2;
lv_obj_t *ui____initial_actions0;


lv_obj_t *modal_Screen;
lv_obj_t *state_tabel;
lv_obj_t *open_modal_btn;
lv_obj_t *setup_set_Screen;
lv_obj_t *tabview_setup_Screen;
lv_obj_t *tabview_grid_Screen;
lv_obj_t *simple_card_game_Screen;
lv_obj_t *simple_card_game_init_Screen;
lv_obj_t *charts_init_Screen;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(lv_disp_t *disp) {
  lv_theme_t *theme = lv_theme_default_init(
      disp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
      false, LV_FONT_DEFAULT);
  lv_disp_set_theme(disp, theme);
  charts_Screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr(charts_init_Screen);
}
